apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-multiple-container
  name: php-multiple-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-multiple-container
  template:
    metadata:
      labels:
        app: php-multiple-container
    spec:
      containers:
        - image: adminvitcon/my-php-app:0.0.1
          name: php
          volumeMounts:
            - name: app-volume
              mountPath: /app
        - image: adminvitcon/my-nginx-app:0.0.2
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-volume
              mountPath: /app
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: default.conf
        - name: app-volume
#          emptyDir: { }
          hostPath:
            path: /app