apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: php-multiple-container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Укажите нужный вам порт для доступа
  selector:
    app: php-multiple-container